on: pull_request
name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.0,name=iPhone X', 'platform=tvOS Simulator,OS=12.0,name=Apple TV 4K']
    steps:
      - uses: actions/checkout@master
      - run: |
        cd Texstyle
        xcodebuild clean test -project Texstyle.xcodeproj -scheme Texstyle