on: pull_request
name: Test
jobs:
  lint:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        DESTINATION: ["platform=iOS Simulator,OS=12.0,name=iPhone X", "platform=tvOS Simulator,OS=12.0,name=Apple TV 4K"]
    steps:
    - uses: actions/checkout@master
    - uses: cd Texstyle
    - uses: xcodebuild clean test -project Texstyle.xcodeproj -scheme Texstyle -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - uses: bash <(curl -s https://codecov.io/bash)
